workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz"  # Il token Expo
      node: "16.14"  # Specifica la versione di Node.js
    scripts:
      - npm install -g expo-cli  # Installa Expo CLI globalmente
      - npm install -g eas-cli  # Installa EAS CLI per la build
      - npm install --legacy-peer-deps  # Risolvi i conflitti delle dipendenze
      - npm install  # Installa tutte le dipendenze, inclusa react-native
      - expo install  # Installa le dipendenze di Expo
      - yarn install || true  # Usa yarn solo se necessario (altrimenti ignora errori)
      
      # Correggi le dipendenze con npx expo-doctor
      - npx expo-doctor  # Usa npx per diagnosticare e risolvere le dipendenze incompatibili
      
      # Verifica le versioni di Expo e React Native
      - expo --version  # Verifica la versione di Expo CLI
      - npx react-native --version  # Verifica la versione di React Native

      # Pulisci la cache di Expo (facoltativo)
      - expo start -c  # Pulisce la cache di Expo

      # Esegui la build con EAS per Android senza pubblicarla
      - eas build --platform android --no-publish  # Usa EAS per la build Android

    artifacts:
      - build/  # Specifica dove trovare i file di output, ad esempio per APK o AAB
