workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz"  # Il token Expo, assicurati di aggiornarlo se necessario
    scripts:
      # Installa Expo CLI globalmente
      - npm install -g expo-cli
      
      # Installa tutte le dipendenze con --legacy-peer-deps per evitare conflitti di versione
      - npm install --legacy-peer-deps

      # Installa le dipendenze di Expo (necessario per il corretto funzionamento di Expo)
      - expo install
      
      # Installa eventuali altre dipendenze
      - yarn install  # Usa yarn se preferisci rispetto a npm

      # Esegui la build per Android
      - expo build:android --no-publish

