workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "<your_expo_token>"
    scripts:
      # Install necessary dependencies before building the app
      - npm install
      - expo install react-native
      - expo install
      - yarn install  # If you're using yarn instead of npm
      - expo build:android --no-publish
    android:
      build:
        workflow: managed