workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz"  # Il token Expo, assicurati di aggiornarlo se necessario
    scripts:
      - npm install -g expo-cli
      - npm install --legacy-peer-deps
      - expo install
      - yarn install
      - expo build:android --no-publish
