workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz"  # Il tuo token Expo
        EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK: "false"  # Disabilita temporaneamente il controllo Directory
      node: "18"  # Usa Node.js 18 per supportare `fetch` nativamente
    scripts:
      # Installa gli strumenti necessari
      - npm install -g expo-cli eas-cli  # Installa Expo CLI e EAS CLI globalmente
      - npm install --legacy-peer-deps  # Risolvi conflitti di dipendenze
      - npm install  # Installa le dipendenze

      # Sincronizza e risolvi le dipendenze con Expo
      - npx expo install --check  # Controlla e aggiorna automaticamente le dipendenze
      - expo install expo-camera  # Specifica una versione compatibile con il tuo SDK
      - expo install  # Installa eventuali altre dipendenze richieste

      # Verifica la configurazione
      - echo "Verificando configurazione del progetto..."
      - expo --version  # Verifica la versione di Expo CLI
      - npx react-native --version  # Verifica la versione di React Native

      # Pulisci la cache (opzionale)
      - expo start -c  # Pulisci la cache di Expo

      # Avvia la build Android senza pubblicarla
      - eas build --platform android --no-publish  # Usa EAS per creare la build Android

    artifacts:
      - build/  # Specifica dove trovare gli output della build (es. APK/AAB)
