workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz"  # Il token Expo
      node: "16.14"  # Specifica la versione di Node.js
    scripts:
      # Installa Expo CLI globalmente
      - npm install -g expo-cli 
      
      # Installa le dipendenze del progetto, gestendo eventuali conflitti
      - npm install --legacy-peer-deps

      # Installa le dipendenze richieste da Expo
      - expo install 

      # Installa eventuali altre dipendenze tramite Yarn, se necessario
      - yarn install || true  # Usa yarn solo se il tuo progetto lo richiede (aggiungi `|| true` per ignorare eventuali errori se yarn non è necessario)
      
      # Esegui la build per Android senza pubblicarla
      - expo build:android --no-publish 

    artifacts:
      - build/  # Specifica dove trovare i file di output, ad esempio per APK o AAB
