workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz"
        EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK: "false"  # Disabilita il controllo Directory
      node: "18"  # Usa Node.js 18
    scripts:
      - echo "== Verifica versione di Node.js ==" 
      - node -v  # Verifica la versione di Node.js

      - echo "== Installazione degli strumenti ==" 
      - npm install -g expo-cli eas-cli  # Installa Expo CLI e EAS CLI
      - npm install --legacy-peer-deps  # Risolvi conflitti di dipendenze, se necessario

      - echo "== Aggiornamento delle dipendenze con expo install --fix =="
      - npx expo install --fix  # Risolve le versioni incompatibili automaticamente

      - echo "== Build con EAS =="
      - eas build --platform android --non-interactive  # Costruisci l'app senza pubblicarla

    artifacts:
      - build/  # Specifica dove trovare gli output della build (APK/AAB)
