workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz"
    scripts:
      # Installa Expo CLI globalmente
      - npm install -g expo-cli
      # Installa le dipendenze del progetto, risolvendo i conflitti
      - npm install --legacy-peer-deps
      - expo install react-native
      - expo install
      - yarn install  # Usa questo solo se preferisci yarn
      # Esegui la build per Android
      - expo build:android --no-publish
