workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz"
    scripts:
      # Installa Expo CLI globalmente
      - npm install -g expo-cli
      # Forza l'installazione delle dipendenze con --legacy-peer-deps
      - npm install --legacy-peer-deps
      # Installa le dipendenze richieste da Expo
      - expo install
      - yarn install # Usa yarn se preferisci
      # Esegui la build per Android
      - expo build:android --no-publish
