workflows:
  expo_workflow:
    name: Expo Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: "-yOXhrRGGMdpm8XbR_UR1NbZdppU44Fdm4-PsOGz" # Il token Expo
      node: "16.x" # Specifica la versione di Node.js
    scripts:
      - npm install -g expo-cli # Installa Expo CLI globalmente
      - npm install --legacy-peer-deps # Risolvi i conflitti delle dipendenze
      - expo install # Installa le dipendenze richieste da Expo
      - yarn install # Installa eventuali altre dipendenze (opzionale)
      - expo build:android --no-publish # Esegui la build per Android
    artifacts:
      - build/ # Specifica dove trovare i file di output, ad esempio per APK o AAB